### ISSUE TITLE
error after entering python hunyuanvideo_gradio.py

### ISSUE THREAD

**Issue by J-Ai-57** [newgenai79/newgenai#8]
Successfully downloaded: hunyuan-video-t2v-720p-Q3_K_S.gguf
Traceback (most recent call last):
  File "D:\newgenai\HunyuanVideo\hunyuanvideo_gradio.py", line 158, in <module>
    transformer = HunyuanVideoTransformer3DModel.from_single_file(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\newgenai\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\newgenai\venv\Lib\site-packages\diffusers\loaders\single_file_model.py", line 236, in from_single_file
    checkpoint = load_single_file_checkpoint(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\newgenai\venv\Lib\site-packages\diffusers\loaders\single_file_utils.py", line 387, in load_single_file_checkpoint
    pretrained_model_link_or_path = _get_model_file(
                                    ^^^^^^^^^^^^^^^^
  File "D:\newgenai\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\newgenai\venv\Lib\site-packages\diffusers\utils\hub_utils.py", line 309, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named hunyuan-video-t2v-720p-Q3_K_M.gguf found in directory city96/HunyuanVideo-gguf.

(venv) D:\newgenai\HunyuanVideo>

**Comment by nitinmukesh** [comment]
Please download the change, it was typo error in code
git pull

**Comment by J-Ai-57** [comment]
Should I git pull again?

**Comment by nitinmukesh** [comment]
Yes. let me know if it worked or not.

**Comment by J-Ai-57** [comment]
the result is the following: D:\newgenai\HunyuanVideo>python HunyuanVideo_gradio.py
  File "D:\newgenai\HunyuanVideo\HunyuanVideo_gradio.py", line 100
    <title>newgenai/HunyuanVideo/HunyuanVideo_gradio.py at main · newgenai79/newgenai</title>
                                                                ^
SyntaxError: invalid character '·' (U+00B7)

D:\newgenai\HunyuanVideo>

**Comment by nitinmukesh** [comment]
Git pull one more time and check plz

**Comment by J-Ai-57** [comment]
success! Thank you

**Comment by nitinmukesh** [comment]
Thank you for trying multiple fixes
